In [1]:
import pandas as pd
import datetime as dt

from sqlalchemy import create_engine

import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, func

import os
# Set up directories
input_dir = 'input_data'
landing_dir = 'landing_data'
cleaned_dir = 'cleaned_data'

PSQL_USER='toddh'
PSQL_PWD='heritage'

In [2]:
# read cleaned pollution file.
POLLUTION_FILE = os.path.join( cleaned_dir, 'cleaned_pollution.csv')

pollution_df = pd.read_csv(POLLUTION_FILE)
pollution_df.head()

   Unnamed: 0  Year State O3_Units_Measurement    O3_min    O3_max   O3_Mean
0           0  2013    AL    Parts per million  0.000000  0.026333  0.012099
1           1  2013    AR    Parts per million  0.003292  0.049000  0.025577
2           2  2013    AZ    Parts per million  0.002000  0.059750  0.027973
3           3  2013    CA    Parts per million  0.000000  0.071167  0.026075
4           4  2013    CO    Parts per million  0.000083  0.057100  0.028709

In [3]:
# read cleaned asthma file.
ASTHMA_FILE = os.path.join( cleaned_dir, 'cleaned_asthma.csv')

asthma_df = pd.read_csv(ASTHMA_FILE)
asthma_df.head()

,Asthma Sample Size,Asthma Prevalence (%),Standard Error,95% CI* (%),Year
0,4564.0,14.8,0.83,(13.2 – 16.4),2013
1,4375.0,12.4,0.70,(11.1 – 13.8),2014
2,3642.0,13.4,1.02,(11.4 – 15.4),2015
3,2906.0,14.2,1.08,(12.1–16.4),2016
4,6484.0,13.6,0.61,(12.4 – 14.8),2013

In [4]:
# Connect to the database

rds_connection_string = f'{PSQL_USER}:{PSQL_PWD}@localhost:5432/pollution'
engine = create_engine(f'postgresql://{rds_connection_string}')

In [7]:
# load database pollution
pollution_df.to_sql(name='cleaned_pollution', con=engine, if_exists='append', index=False)

In [8]:
# load database asthma
asthma_df.to_sql(name='asthma_df', con=engine, if_exists='append', index=False)

ProgrammingError: (psycopg2.ProgrammingError) incomplete placeholder: '%(' without ')'
[SQL: INSERT INTO asthma_df ("Asthma Sample Size", "Asthma Prevalence (%%)", "Standard Error", "95%% CI* (%%)", "Year") VALUES (%(Asthma Sample Size)s, %(Asthma Prevalence (%))s, %(Standard Error)s, %(95% CI* (%))s, %(Year)s)]
[parameters: ({'Asthma Sample Size': 4564.0, 'Asthma Prevalence (%)': 14.8, 'Standard Error': 0.83, '95% CI* (%)': '(13.2 – 16.4)', 'Year': 2013}, {'Asthma Sample Size': 4375.0, 'Asthma Prevalence (%)': 12.4, 'Standard Error': 0.7, '95% CI* (%)': '(11.1 – 13.8)', 'Year': 2014}, {'Asthma Sample Size': 3642.0, 'Asthma Prevalence (%)': 13.4, 'Standard Error': 1.02, '95% CI* (%)': '(11.4 – 15.4)', 'Year': 2015}, {'Asthma Sample Size': 2906.0, 'Asthma Prevalence (%)': 14.2, 'Standard Error': 1.08, '95% CI* (%)': '(12.1–16.4)', 'Year': 2016}, {'Asthma Sample Size': 6484.0, 'Asthma Prevalence (%)': 13.6, 'Standard Error': 0.61, '95% CI* (%)': '(12.4 – 14.8)', 'Year': 2013}, {'Asthma Sample Size': 8620.0, 'Asthma Prevalence (%)': 14.6, 'Standard Error': 0.56, '95% CI* (%)': '(13.5 – 15.7)', 'Year': 2014}, {'Asthma Sample Size': 7924.0, 'Asthma Prevalence (%)': 15.6, 'Standard Error': 0.58, '95% CI* (%)': '(14.5 – 16.8)', 'Year': 2015}, {'Asthma Sample Size': 7015.0, 'Asthma Prevalence (%)': 14.9, 'Standard Error': 0.6, '95% CI* (%)': '(13.8–16.1)', 'Year': 2016}  ... displaying 10 of 204 total bound parameter sets ...  {'Asthma Sample Size': 5465.0, 'Asthma Prevalence (%)': 13.5, 'Standard Error': 0.79, '95% CI* (%)': '(12.0 – 15.0)', 'Year': 2015}, {'Asthma Sample Size': 4487.0, 'Asthma Prevalence (%)': 13.9, 'Standard Error': 0.86, '95% CI* (%)': '(12.2–15.6)', 'Year': 2016})]
(Background on this error at: http://sqlalche.me/e/f405)